### ISSUE TITLE
适配的是哪个版本的客户端？

### ISSUE THREAD

**Issue by aerbig** [match5/thsauto#4]
适配的是哪个版本的客户端？复制持仓现在不都会让填写验证码了吗？

**Comment by match5** [comment]
现在新的客户端不需要验证码

**Comment by wdl5i** [comment]
你好，不知道你是在什么环境下跑的，我是跑在阿里云的windows server 2019上的，64位机，经常会出现(5, 'SetCursorPos', '拒绝访问')的错误，特别是我要查询当前持仓的时候，特别容易出现，现在的自动交易程序因为这个不稳定因素，执行不下去了，请教，多谢指点

**Comment by match5** [comment]
我是在win10虚拟机上跑的 没有试过win server
还有云主机是否能控制鼠标也不太清楚
实在不行就把refresh的调用去掉
