### ISSUE TITLE
(5, 'SetCursorPos', '拒绝访问')

### ISSUE THREAD

**Issue by wdl5i** [match5/thsauto#5]
你好，不知道你是在什么环境下跑的，我是跑在阿里云的windows server 2019上的，64位机，经常会出现(5, 'SetCursorPos', '拒绝访问')的错误，特别是我要查询当前持仓的时候，特别容易出现，现在的自动交易程序因为这个不稳定因素，执行不下去了，请教，多谢指点

**Comment by match5** [comment]
我是在win10虚拟机上跑的 没有试过win server
还有云主机是否能控制鼠标也不太清楚
多桌面的话要保证客户端运行再当前桌面
实在不行就把refresh的调用去掉

**Comment by wdl5i** [comment]
我测试了一台win10主机，一台阿里云win server 2019, 一台华为云win server 2019, 目前只在阿里云服务器上出现过这个现象，而且半多是在1个小时以上没有动过对应的主机时下才会出现(整个过程始终保持同花顺下单程序在前台运行)，但如果根据自已定的交易策略，重仓的情况下做自动交易，遇到这种情况损失还是比较大的，希望有好的办法可以解决，如果不用win32api，用其他的库，不知道可不可行？谢谢你的回复

**Comment by weue** [comment]
是否方便说下你的运行环境以及依赖的版本呢？我这边无法正常运行。

**Comment by match5** [comment]
> 是否方便说下你的运行环境以及依赖的版本呢？我这边无法正常运行。

你具体报什么错
python版本是3.6
其他的包找不到直接pip install一下就行

**Comment by weue** [comment]
> > 是否方便说下你的运行环境以及依赖的版本呢？我这边无法正常运行。
> 
> 你具体报什么错
> python版本是3.6
> 其他的包找不到直接pip install一下就行

    length = ctypes.windll.user32.SendMessageW(hwnd, win32con.WM_GETTEXTLENGTH)
ValueError: Procedure probably called with not enough arguments (8 bytes missing)
首先是这个错误，然后我在thsauto.py修改42行length = ctypes.windll.user32.SendMessageW(hwnd, win32con.WM_GETTEXTLENGTH, 0, 0)这个错误没了。

然后get_position无法正常工作。所以感觉可能是环境版本的问题。
我的环境是：
win10  64位
python  3.6    32位


Package         Version
--------------- -------------------
beautifulsoup4  4.9.1
bs4             0.0.1
certifi         2020.6.20
chardet         3.0.4
click           7.1.2
comtypes        1.1.7
Flask           1.1.2
idna            2.10
itsdangerous    1.1.0
Jinja2          2.11.2
MarkupSafe      1.1.1
numpy           1.19.1
pandas          0.23.0
Pillow          7.2.0
pip             20.2.2
pypiwin32       223
python-dateutil 2.8.1
pytz            2020.1
pywin32         228
pywinauto       0.6.6
requests        2.24.0
scikit-learn    0.20.2
scipy           1.1.0
setuptools      49.6.0.post20200814
six             1.15.0
soupsieve       2.0.1
urllib3         1.25.10
Werkzeug        1.0.1
wheel           0.34.2
wincertstore    0.2

**Comment by weue** [comment]
![image](https://user-images.githubusercontent.com/28719349/90414000-cecc9980-e0e1-11ea-84ac-80b1cbee4c12.png)

**Comment by match5** [comment]
> ![image](https://user-images.githubusercontent.com/28719349/90414000-cecc9980-e0e1-11ea-84ac-80b1cbee4c12.png)
> 
> 

我这里用的网上交易系统5.0 你这个6.3我还没有用过

**Comment by match5** [comment]
这是我的客户端版本
![}FA%4V UT159C()STH$RL{A](https://user-images.githubusercontent.com/3426096/90419101-a4caa580-e0e8-11ea-9d59-d94cd3821dcb.png)
![5F)J}VLKC1SHP$Q@I~$VT@A](https://user-images.githubusercontent.com/3426096/90419109-a8f6c300-e0e8-11ea-945c-4a3660c7d559.png)

**Comment by weue** [comment]
非常感谢你的解答，是THS版本问题，已经换低版本解决了🤝

**Comment by iniwf** [comment]
> 非常感谢你的解答，是THS版本问题，已经换低版本解决了🤝

换了哪个版本？哪里下载？谢谢
