### ISSUE TITLE
撤单出现，没找到指定订单

### ISSUE THREAD

**Issue by manyhelp** [match5/thsauto#9]
下单成功，返回订单编号12，调用撤单，就提示没找到指定订单

**Comment by match5** [comment]
> 下单成功，返回订单编号12，调用撤单，就提示没找到指定订单

有些版本的 xiadan.exe 使用 ctrl+c 复制有问题
可以尝试改为使用右键菜单复制
idx 参数为 “复制” 在菜单中的位置索引
thsauto.py
341        # self.right_click_menu(ctrl, -50, -50, idx=3)         改为               self.right_click_menu(ctrl, -50, -50, idx=3)
342        win32gui.SetForegroundWindow(ctrl)                                          #win32gui.SetForegroundWindow(ctrl)
343        hot_key(['ctrl', 'c'])                                                                          #hot_key(['ctrl', 'c'])

类似的复制操作 还有几处 代码中都保留了 使用右键菜单的注释代码 可根据情况自己调整下
